apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: default
  labels:
    app: maintenance-service
spec:
  type: ClusterIP
  selector:
    app: maintenance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
