apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-service
  namespace: default
  labels:
    app: maintenance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance-service
  template:
    metadata:
      labels:
        app: maintenance-service
    spec:
      containers:
        - name: maintenance-service
          image: maintenance-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_DB
              value: "maintenance_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
