apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: default
  labels:
    app: vehicle-service
spec:
  type: ClusterIP
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
